name: Vocabulary Reminder

on:
  schedule:
    - cron: '0 */2 * * *'  # Co 2 godziny
  workflow_dispatch:       # Możliwość ręcznego uruchomienia

jobs:
  notify:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Sprawdź i zainstaluj jq
        run: |
          if ! command -v jq &> /dev/null; then
            brew install jq
          fi

      - name: Ustaw uprawnienia do skryptu
        run: chmod +x vocab.sh  # Poprawiona ścieżka

      - name: Uruchom skrypt
        run: ./vocab.sh  # Poprawiona ścieżka
