name: Vocabulary Reminder

on:
  schedule:
    - cron: '0 */4 * * *'  # Co 4 godziny
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Zainstaluj curl i jq
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Ustaw uprawnienia do skryptu
        run: chmod +x vocab.sh

      - name: Uruchom skrypt
        run: ./vocab.sh
