name: Vocabulary Reminder

on:
  schedule:
    - cron: '0 */4 * * *'  # Co 4 godziny
  workflow_dispatch:        # Możliwość ręcznego uruchomienia

jobs:
  notify:
    runs-on: ubuntu-latest   # Linux! (tańsze!)

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Zainstaluj jq (jeśli potrzeba)
        run: |
          if ! command -v jq &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y jq
          fi

      - name: Ustaw uprawnienia do skryptu
        run: chmod +x voc_eng.sh

      - name: Uruchom skrypt
        run: ./voc_eng.sh
